spring:
  profiles:
    active:
      -dev
---
server:
  port: 8201
spring:
  application:
    name: cloud-config-client
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:8001/eureka/
---
server:
  port: 8202
spring:
  application:
    name: cloud-config-client
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:8001/eureka/